version: "3.9"

services:
  api-dev:
    image: node:20-slim
    working_dir: /app
    container_name: application-dev
    env_file:
      - .env
    environment:
      NODE_ENV: development
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
